spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**

server:
  port: 8088

management:
  endpoints:
    web:
      exposure:
        include: health,info,env
