spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**

server:
  port: 8088

eureka:
  instance:
    hostname: ${app.host}
    prefer-ip-address: false
    non-secure-port-enabled: true
    non-secure-port: ${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health,info,env
