spring:
  config:
    activate:
      on-profile: default

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

    service-url:
      defaultZone: http://eureka-server:8761/eureka/

  instance:
    prefer-ip-address: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
