spring:
  kafka:
    bootstrap-servers: kafka:9092

    consumer:
      group-id: notification-group-v2
      auto-offset-reset: earliest
      enable-auto-commit: true

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring:
          json:
            use:
              type:
                headers: false
            trusted:
              packages: ru.microserviceslab.notificationservice.event
            value:
              default:
                type: ru.microserviceslab.events.UserCreatedEvent

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info,env

info:
  app:
    name: Notification Service
    description: Kafka consumer
    version: 1.0.0
