spring:
  kafka:
    bootstrap-servers: 192.168.1.77:9092

    consumer:
      group-id: notification-group-v2
      auto-offset-reset: earliest
      enable-auto-commit: true

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring:
          json:
            use:
              type:
                headers: false
            trusted:
              packages: ru.microserviceslab.notificationservice.event
            value:
              default:
                type: ru.microserviceslab.events.UserCreatedEvent

server:
  port: 8082

eureka:
  instance:
    hostname: ${app.host}
    prefer-ip-address: false
    non-secure-port-enabled: true
    non-secure-port: ${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health,info,env
